### ISSUE TITLE
Support Windows arm64 via the win32-x64 variant

### ISSUE THREAD

**Issue by chadlwilson** [sass/embedded-host-node#263]
Currently if you try and install this on Windows 11 Arm64 no native variant is installed, and at runtime you will get

```
[webpack-cli] Error: Embedded Dart Sass couldn't find the embedded compiler executable. Please make sure the optional dependency sass-embedded-win32-arm64 is installed in node_modules.
    at C:\project\node_modules\sass-embedded\lib\src\compiler-path.ts:52:9
    at Object.<anonymous> (C:\project\node_modules\sass-embedded\lib\src\compiler-path.ts:58:3)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Object.require.extensions.<computed> [as .js] (C:\project\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\project\node_modules\sass-embedded\lib\src\async-compiler.ts:9:1)
```

I've successfully used Dart Sass (native x64) [via Ruby](https://github.com/ntkme/sass-embedded-host-ruby) on Windows via emulation (ruby host uses [this logic](https://github.com/ntkme/sass-embedded-host-ruby/blob/b2380b96c2e398605f440aaaf1138825a1acd9d7/ext/sass/Rakefile#L262-L275)) which is still much faster than old variants.

Short of a full arm64 win32 compile of Dart Sass, could this project be changed to fall back to install and expect `win32-x64` when it otherwise would desire `win32-arm64`? Would such a PR be considered?

**Comment by chadlwilson** [comment]
Cool, thanks! I wonder if this would this be a good use of time in the first place, as I understand the Dart SDK has Windows arm64 support. Having said that, perhaps this isn't something the dart-sass team would be comfortable building and supporting at this stage.

**Comment by nex3** [comment]
Dart support for Windows ARM64 is still experimental. If this is a high priority for you, we'd be happy to take a PR to use x64 instead until it's stable and we can release proper ARM64 support.

**Comment by chadlwilson** [comment]
Oh, wow, thanks @ntkme and 👋
