### ISSUE TITLE
Cant rnm run dev React project via Vite

### ISSUE THREAD

**Issue by MercuryHgO** [sass/embedded-host-node#354]
When trying to `npm run dev` my react project that uses sass, this error occurs:
```
  VITE v6.0.3  ready in 264 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:962:11)
    at Socket._write (node:net:974:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at AsyncCompiler.writeStdin (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/async.js:60:28)
    at PacketTransformer.writeInboundBuffer (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/async.js:114:18)
    at PacketTransformer.writeInboundProtobuf (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/packet-transformer.js:68:18)
    at MessageTransformer.writeInboundProtobuf (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/async.js:116:146)
    at MessageTransformer.writeInboundMessage (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/message-transformer.js:45:18)
    at Dispatcher.writeInboundMessage (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/utils.js:26:123)
    at Dispatcher.sendCompileRequest (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/dispatcher.js:112:18)
    at /home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/async.js:85:77
    at new Promise (<anonymous>)
    at AsyncCompiler.compileRequestAsync (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/async.js:85:33)
    at AsyncCompiler.compileStringAsync (/home/bittermann/projects/sound-system/sound-studio/node_modules/sass-embedded/dist/lib/src/compiler/async.js:126:21)
    at Object.run (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:49009:37)
    at async process (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:49068:24)
    at async compileCSSPreprocessors (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:48168:28)
    at async compileCSS (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:48226:32)
    at async TransformPluginContext.transform (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:47598:11)
    at async EnvironmentPluginContainer.transform (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:47001:18)
    at async loadAndTransform (file:///home/bittermann/projects/sound-system/sound-studio/node_modules/vite/dist/node/chunks/dep-yUJfKD1i.js:40852:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by MercuryHgO** [comment]
> What’s your OS and version?

NixOS 24.05
Nixpkgs version 24.11

**Comment by ntkme** [comment]
It’s currently expected to be broken on NixOS.

See discussion in #334

**Comment by MercuryHgO** [comment]
> It’s currently expected to be broken on NixOS.
> 
> See discussion in #334

Ok, thank you

For those who encounter this issue on NixOS, use FHS Environment in your build/dev shells:
```nix
{
  inputs = {
    nixpkgs.url = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";

  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        libraries = with pkgs;[
          webkitgtk
          gtk3
          cairo
          gdk-pixbuf
          glib
          dbus
          openssl_3
          librsvg
        ];

        packages = pkgs: (with pkgs; [
          curl
          wget
          pkg-config
          dbus
          openssl_3
          glib
          gtk3
          libsoup
          webkitgtk
          librsvg
          nodejs_18
        ]);
      in
      {
        devShell = (pkgs.buildFHSEnv {
          name = "sound-system";
          targetPkgs = packages;

          profile =
            ''
              export LD_LIBRARY_PATH=${pkgs.lib.makeLibraryPath libraries}:$LD_LIBRARY_PATH
              export XDG_DATA_DIRS=${pkgs.gsettings-desktop-schemas}/share/gsettings-schemas/${pkgs.gsettings-desktop-schemas.name}:${pkgs.gtk3}/share/gsettings-schemas/${pkgs.gtk3.name}:$XDG_DATA_DIRS
              bash
            '';
        }).env;
      });
}
```
